#layout: page
name: yaaun # Musi być, bo inaczej pojawia się zdwojony tytuł.
title: null # "yaaun’s github page"
theme: minima
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

header_pages:
  - index.md
  - subpage.md
  - wisdom.md